runtime: nodejs
env: flex


env_variables:
  DB_HOST: 34.101.168.24
  DB_USER: root
  DB_PASS: 
  DB_NAME: rempahustle
  INSTANCE_CONNECTION_NAME: rempahustle-project:asia-southeast2:rempahustle-sql

beta_settings: 
  cloud_sql_instances: rempahustle-project:asia-southeast2:rempahustle-sql

entrypoint: npm run start

# runtime_config:
#   nodejs_version: 18